version: 1
services:
  - type: web
    name: heijunka-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn heijunka_project.wsgi --log-file -
    envVars:
      - key: DATABASE_URL
        value: postgresql://heijunka_bd_92vk_user:dijm6RzZ5O7XPSM8dEftuJ8xVtzOZUc4@dpg-cs8jj768ii6s73cd2sp0-a.oregon-postgres.render.com/heijunka_bd_92vk
      - key: SECRET_KEY
        value: 'django-insecure-dsxlmfn(l!&41lp8k_le@7cxyh*^9z#&rvy!vev#^m()0bir-4'
    autoDeploy: true
