# Generated by Django 5.1.1 on 2024-10-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin_su', 'Admin SU'), ('user_ku', 'User KU'), ('user_fnal', 'User Fnal'), (None, 'None')], max_length=10, unique=True),
        ),
    ]
