# Generated by Django 5.1.1 on 2024-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0009_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='roles',
        ),
    ]
