# Generated by Django 5.1.1 on 2024-10-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0010_rename_name_role_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='roles',
            new_name='name',
        ),
    ]
