# Generated by Django 5.1.1 on 2024-10-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0011_rename_roles_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
