# Generated by Django 5.1.1 on 2024-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0012_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'operator')], default='operator', max_length=10),
        ),
    ]
