# Generated by Django 5.1.1 on 2024-10-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0013_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heijunka_app.site'),
        ),
    ]
