# Generated by Django 5.1.1 on 2024-10-17 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heijunka_app', '0015_user_site_taskassignment_taskparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='users',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='collaborator',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'operator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='hour',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='quantity',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heijunka_app.site'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskParameter',
        ),
    ]
